<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SPEAKERS</name>
   <tag></tag>
   <elementGuidId>45a89790-375c-41a1-a70e-6574675a1a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='speakersTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#speakersTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8bffd0a-a8e9-45a4-90bc-f0aad55c5642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speakersTxt</value>
      <webElementGuid>8afa094d-2004-4af0-b8a2-be41a6368f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SpeakersCategoryTxt</value>
      <webElementGuid>9936f2fd-61fc-48d3-ae0a-8f22fcbe6599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>bb961d4f-498a-4f00-ae37-aef109801edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>0727742c-30d3-4d82-b4c8-d9421e67fb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>abf580ea-17ac-47a2-948d-54ed4034edac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPEAKERS</value>
      <webElementGuid>779bc538-db6e-42f7-9d75-53f864d83183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speakersTxt&quot;)</value>
      <webElementGuid>91365459-5355-456f-9729-5953aec811cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='speakersTxt']</value>
      <webElementGuid>8777dc36-695c-4f5a-b3a8-7dbbed1c1d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='speakersImg']/div/span</value>
      <webElementGuid>a88fae33-58fa-4c0c-9234-71877dbc0b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO'])[1]/following::span[4]</value>
      <webElementGuid>2fa1a0f2-0035-4798-ac4a-47d9396370e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dvantage'])[1]/following::span[5]</value>
      <webElementGuid>aad44b29-1505-40dd-a028-b88629a4eab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[1]/preceding::span[1]</value>
      <webElementGuid>caaefd53-d72e-4bca-9fbf-1df020fa507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TABLETS'])[1]/preceding::span[1]</value>
      <webElementGuid>75ad295c-a1ff-46b7-96bb-c36749d40d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SPEAKERS']/parent::*</value>
      <webElementGuid>def48d3c-0853-4815-87cd-6a4bf6580700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>175117d1-6768-4050-ab8f-3b33056046e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'speakersTxt' and @href = 'javascript:void(0)' and (text() = 'SPEAKERS' or . = 'SPEAKERS')]</value>
      <webElementGuid>9f8af20e-969f-4aa7-ace2-7cd6358d6c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
